"""Plain-English instructions written to the sheet's "How To" tab (README has the same, plus developer notes)."""

HOW_TO_TEXT = [
    "HOW TO USE THIS SHEET",
    "",
    "REFRESHING PRICES",
    "• Menu: Prices > Refresh prices. A message says 'Refresh started'. Wait about 2 minutes, then look at the Prices tab.",
    "• Settings > 'Last run' shows when it last ran and how many prices worked or failed.",
    "• Status on the Prices tab: ok = fresh price, used in quotes. stale = today's check failed, the old price is kept for reference but NOT used. failed = no price at all. The 'error' column says why.",
    "• A price older than the 'Stale after (days)' setting is not used, even if it says ok.",
    "",
    "MAKING A QUOTE",
    "• Copy the Quote tab first (right-click the tab > Duplicate) so the template stays clean.",
    "• Pick an item_code from the dropdown in column A and type the qty. Timber qty is in metres, sheets per sheet, bags per bag, fixings each.",
    "• Description, unit, waste %, cheapest price and supplier fill in by themselves. You can type over waste % or markup % on any line.",
    "• Labour or extras: leave item_code empty, then type over the description, qty, unit and 'cheapest unit price' cells with your own values.",
    "• 'NO PRICE' means no supplier has a fresh, valid price. Fix the item (see below) or put a price in manual_override_price on the Items tab.",
    "• Totals ex VAT, VAT and inc VAT are at the bottom.",
    "",
    "ADDING A NEW ITEM (Items tab)",
    "1. Write the exact spec in the 'spec' column: grade, treatment, finished size, length. Be precise. This is what you check supplier pages against.",
    "2. Give it a short unique item_code, e.g. TIM-C16-3X2-3.0.",
    "3. Pick the canonical_unit: timber = m (per metre), sheet goods = sheet, bagged = bag, fixings = each.",
    "4. pack_qty = how many of that unit you get for one listed price. A 2.4m length = 2.4. A box of 200 screws = 200. One sheet = 1.",
    "5. Find the product on each supplier's website. Only use it if it truly matches the spec. For B&Q, check the page says it's sold by B&Q, not a marketplace seller.",
    "6. Paste each product page address into that supplier's _url column. If a supplier sells a different pack size, put it in that supplier's _pack_qty column.",
    "7. No true match at a supplier? Leave that URL blank and say why in 'notes'.",
    "8. Set default_waste_pct (e.g. 10%). Then run Prices > Refresh prices.",
    "",
    "MANUAL PRICES",
    "• manual_override_price on the Items tab is ex VAT per canonical unit (per metre, per sheet...). If filled it always wins and the supplier shows as 'Manual'. Clear it to go back to scraped prices.",
    "",
    "ADDING A NEW SUPPLIER (e.g. Travis Perkins)",
    "• This needs a small change in the GitHub project (suppliers.yaml). See the README there, or ask whoever set this up.",
    "• Then add two columns to the right of the Items tab named exactly like the new supplier's url_column and <key>_pack_qty, and paste URLs in.",
    "",
    "DON'T",
    "• Don't rename tabs, or reorder Items columns A to H. Formulas rely on them.",
    "• Don't type into the Prices tab. The refresh overwrites it.",
    "",
    "ONE-TIME SETUP",
    "• Step-by-step setup (Google service account, sharing, GitHub token) is in the README of the GitHub project.",
]
